export const gbufferScreenSpaceRaymarchDepthFragmentTemplate = `#version 300 es
precision highp float;
#pragma DEFINES
#define saturate(a)clamp(a,0.,1.)
float rand(vec2 u){return fract(sin(dot(u.xy,vec2(12.98,78.23)))*43.75);}vec3 hash3(vec3 u){return fract(sin(vec3(dot(u,vec3(127.1,311.7,114.5)),dot(u,vec3(269.5,183.3,191.9)),dot(u,vec3(419.2,371.9,514.1))))*43758.5433);}layout(std140) uniform ubCommon{float uTime;float uDeltaTime;vec4 uViewport;};layout(std140) uniform ubTransformations{mat4 uWorldMatrix;mat4 uViewMatrix;mat4 uProjectionMatrix;mat4 uNormalMatrix;mat4 uInverseWorldMatrix;mat4 uViewProjectionMatrix;mat4 uInverseViewMatrix;mat4 uInverseProjectionMatrix;mat4 uInverseViewProjectionMatrix;mat4 uTransposeInverseViewMatrix;};layout(std140) uniform ubCamera{vec3 uViewPosition;vec3 uViewDirection;float uNearClip;float uFarClip;float uAspect;float uFov;};layout(std140) uniform ubTimeline{float uTimelineTime;float uTimelineDeltaTime;};
#pragma BLOCK_BEFORE_RAYMARCH_CONTENT
#define PI 3.14
#define PI2 6.28
#define OP_ID(p,r)round(p/r)
#define OP_RE(p,r)p-r*round(p/r)
#define OP_LI_RE(p,r,l)p-r*clamp(round(p/r),-l,l)
#define EPS.0001
#define OI 80
#define SI 80
vec2 o(vec2 u,vec2 d){return u.x<d.x?u:d;}mat2 o(float u){float v=sin(u),f=cos(u);return mat2(f,v,-v,f);}vec3 opRe(vec3 u,float y){return u-y*round(u/y);}vec3 opLiRe(vec3 u,float y,vec3 v){return u-y*clamp(round(u/y),-v,v);}vec2 opRo(vec2 u,float d){return u*o(-d);}vec3 opTr(vec3 u,vec3 d){return u-d;}vec3 u(vec3 u,vec3 d){return u/d;}float d(float u,vec3 v){return u*min(v.x,min(v.y,v.z));}vec2 d(vec2 u){float v=PI/10.-atan(u.x,u.y),f=PI*2./10.;v=floor(v/f)*f;return opRo(u,-v);}float opSm(float u,float v,float y){float f=clamp(.5+.5*(v-u)/y,0.,1.);return mix(v,u,f)-y*f*(1.-f);}float dfSp(vec3 u,float d){return length(u)-d;}float dfRb(vec3 u,vec3 d,float v){vec3 f=abs(u)-d;return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.)-v;}float dfBo(vec3 u,vec3 d){vec3 v=abs(u)-d;return length(max(v,0.))+min(max(v.x,max(v.y,v.z)),0.);}float dfTo(vec3 u,vec2 d){return length(vec2(length(u.xz)-d.x,u.y))-d.y;}float dfOc(vec3 u,float d){u=abs(u);return(u.x+u.y+u.z-d)*.577;}float dfCo(vec3 u,vec2 v){vec2 d=vec2(length(u.xz),-u.y);return length(d-v*max(dot(d,v),0.))*(d.x*v.y-d.y*v.x<0.?-1.:1.);}float d(vec3 u,float d,float v){vec2 f=vec2(length(u.xz)-2.*d+.05,abs(u.y)-v);return min(max(f.x,f.y),0.)+length(max(f,0.))-.05;}float opWi(vec3 v,vec3 f,float y,vec2 m){v=opTr(v,vec3(m.xy,0));v.xy=opRo(v.xy,y);v.yz=opRo(v.yz,PI*.5);v=u(v,f);float o=d(v,1.,.1);return d(o,f);}vec2 opBu(vec3 u,float d){u/=1.4;vec3 v=u;v.yz=opRo(v.yz,-PI*.5);vec2 f=vec2(10,.6);v.x=abs(v.x);v.xz=opRo(v.xz,PI*sin(sin(uTimelineTime*f.x+d)*cos(uTimelineTime*f.y+d))*.3);float m=opWi(v,vec3(.4,.3,.24)*.2,PI*-.3,vec2(.5,.4)*.2),y=opWi(v,vec3(.32,.3,.2)*.2,PI*.3,vec2(.4,-.4)*.2);return vec2(min(m,y),0);}vec2 opFl(vec3 v,float y){vec2 f=vec2(1e4,-1e4);v/=1.;v.y-=-.8;float r=.1;r=sin(uTimelineTime*1.4+.2+y)*.5;float m=-.1;m=cos(uTimelineTime*1.6+.1+y)*-.5;float z=v.y*sin(v.y*r),s=v.y*sin(v.y*m),x=sin(1.12*r)*.28,P=sin(1.12*m)*.28;mat2 a=o(-1.12*r),e=o(1.12*m);vec3 l=v;l=opTr(l,vec3(z,.28,s));float p=d(l,.015,.28);f=o(f,vec2(p,1));vec3 i=v;i=opTr(i,vec3(x,.56,P));i.yz=opRo(i.yz,PI*.5);i.xz*=a;i.yz*=e;i.xy=d(i.xy);i=opTr(i,vec3(0,.2,sin(i.y*5.)*.105));i.yz=opRo(i.yz,PI*.5);vec3 S=vec3(.08,.2,.2);i=u(i,S);float O=d(i,.4,.01);O=d(O,S);f=o(f,vec2(O,2));vec3 B=v;B=opTr(B,vec3(x,.59,P));float h=dfSp(B,.04);return o(f,vec2(h,3));}float opDb(float u,float v,float f,float d,float m,float y){return mix(mix(mix(v,f,smoothstep(0.,.25,u)),mix(f,d,smoothstep(.25,.5,u)),smoothstep(.25,.5,u)),mix(mix(d,m,smoothstep(.5,.75,u)),mix(m,y,smoothstep(.75,1.,u)),smoothstep(.5,.75,u)),smoothstep(.5,1.,u));}float opTb(float u,float v,float f,float d){return mix(mix(v,f,smoothstep(0.,.5,u)),mix(f,d,smoothstep(.5,1.,u)),smoothstep(.5,1.,u));}
#define BN 16
#define FS 1.4
#define CS.25
#define MS.35
uniform vec3 uCP,uBPs[BN],uGPs[4];uniform float uGS;uniform vec4 uGSs[4];uniform float uOMR;uniform vec3 uORo;uniform float uMR;float u(vec3 u){return sin(u.x*4.+uTimelineTime*3.4)*.025+.025+(cos(u.y*3.+uTimelineTime*3.2)*.025+.025)+(sin(u.z*3.5+uTimelineTime*3.)*.025+.025)+.01;}float dfMC(vec3 u){return dfSp(u,FS);}float diMAt(vec3 u){return 1.-smoothstep(1.,1.8,length(u-uCP));}float dfMB(vec3 v,float f){for(int d=0;d<BN;d++){vec3 m=opTr(v,uBPs[d].xyz);float y=dfSp(m,CS*uGS);f=opSm(f,y,MS);}f+=u(v)*diMAt(v)*uGS;return f;}float dfMBs(vec3 u){float v=dfSp(opTr(u,uCP),FS*uGS);return dfMB(u,v);}vec2 opMo(vec2 u,vec2 v,float f){return mix(u,v,f);}vec2 o(vec3 u,float v,float f){vec3 d=mod(u*f,2.)-1.;f*=3.;vec3 m=abs(1.-3.*abs(d));float y=(min(max(m.x,m.y),min(max(m.y,m.z),max(m.z,m.x)))-1.)/f;return vec2(max(v,y),f);}float dfMe(vec3 u,float d){u/=d;u/=.5;float v=dfBo(u,vec3(1));vec2 f=vec2(v,1);f=o(u,f.x,f.y);f=o(u,f.x,f.y);f=o(u,f.x,f.y);return f.x*d;}vec3 opPrf(vec3 u,float v,float d){u=abs(u)-1.18;u=abs(u)-1.2;u.xz*=o(v+.1+uTimelineTime*.8+d);u.xy*=o(v+.8+sin(uTimelineTime)*.4+d);return u;}float dfPr(vec3 u,float v,float d){u/=d;vec3 f=u;f.xy*=o(uTimelineTime*.8+v);float m=dfTo(f,vec2(.8,.05));vec3 i=u;i.yz*=o(uTimelineTime*1.2+v);float y=dfTo(i,vec2(.8,.05)),x=dfOc(u,.6),s=opSm(opSm(m,y,.5),x,.5);return s*d;}
#pragma RAYMARCH_SCENE
float u(float u,float v,float d){return(u+v)/(v-d);}float n(float u,float v,float d){float f=v*u;return-f/(d*(u-1.)-f);}uniform sampler2D uDepthTexture;in vec2 vUv;out vec4 outColor;void main(){vec3 d=uViewPosition,f=vec3(0,0,-1);vec2 v=vec2(0);float m=0.;vec3 y=d;float o=EPS;for(int r=0;r<SI;r++){y=d+f*m;v=dfScene(y);m+=v.x;if(v.x<=o)break;}if(v.x>o)discard;float i=texelFetch(uDepthTexture,ivec2(gl_FragCoord.xy),0).x,s=n(i,uNearClip,uFarClip),x=u((uViewMatrix*vec4(y,1)).z,uNearClip,uFarClip);if(x>s)discard;outColor=vec4(1);}`;