export const litScreenSpaceRaymarchFragmentTemplate = `#version 300 es
precision highp float;
#pragma DEFINES
#define saturate(a)clamp(a,0.,1.)
float rand(vec2 u){return fract(sin(dot(u.xy,vec2(12.98,78.23)))*43.75);}vec3 hash3(vec3 u){return fract(sin(vec3(dot(u,vec3(127.1,311.7,114.5)),dot(u,vec3(269.5,183.3,191.9)),dot(u,vec3(419.2,371.9,514.1))))*43758.5433);}layout(std140) uniform ubCommon{float uTime;float uDeltaTime;vec4 uViewport;};layout(std140) uniform ubTransformations{mat4 uWorldMatrix;mat4 uViewMatrix;mat4 uProjectionMatrix;mat4 uNormalMatrix;mat4 uInverseWorldMatrix;mat4 uViewProjectionMatrix;mat4 uInverseViewMatrix;mat4 uInverseProjectionMatrix;mat4 uInverseViewProjectionMatrix;mat4 uTransposeInverseViewMatrix;};layout(std140) uniform ubCamera{vec3 uViewPosition;vec3 uViewDirection;float uNearClip;float uFarClip;float uAspect;float uFov;};layout(std140) uniform ubTimeline{float uTimelineTime;float uTimelineDeltaTime;};
#pragma BLOCK_BEFORE_RAYMARCH_CONTENT
#define PI 3.14
#define PI2 6.28
#define OP_ID(p,r)round(p/r)
#define OP_RE(p,r)p-r*round(p/r)
#define OP_LI_RE(p,r,l)p-r*clamp(round(p/r),-l,l)
#define EPS.0001
#define OI 80
#define SI 80
vec2 o(vec2 u,vec2 d){return u.x<d.x?u:d;}mat2 o(float u){float v=sin(u),f=cos(u);return mat2(f,v,-v,f);}vec3 opRe(vec3 u,float o){return u-o*round(u/o);}vec3 opLiRe(vec3 u,float o,vec3 v){return u-o*clamp(round(u/o),-v,v);}vec2 opRo(vec2 u,float v){return u*o(-v);}vec3 opTr(vec3 u,vec3 o){return u-o;}vec3 u(vec3 u,vec3 o){return u/o;}float d(float u,vec3 v){return u*min(v.x,min(v.y,v.z));}vec2 d(vec2 v){float u=PI/10.-atan(v.x,v.y),f=PI*2./10.;u=floor(u/f)*f;return opRo(v,-u);}float opSm(float u,float v,float o){float f=clamp(.5+.5*(v-u)/o,0.,1.);return mix(v,u,f)-o*f*(1.-f);}float dfSp(vec3 u,float o){return length(u)-o;}float dfRb(vec3 u,vec3 o,float v){vec3 f=abs(u)-o;return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.)-v;}float dfBo(vec3 u,vec3 o){vec3 v=abs(u)-o;return length(max(v,0.))+min(max(v.x,max(v.y,v.z)),0.);}float dfTo(vec3 v,vec2 u){return length(vec2(length(v.xz)-u.x,v.y))-u.y;}float dfOc(vec3 u,float o){u=abs(u);return(u.x+u.y+u.z-o)*.577;}float dfCo(vec3 u,vec2 v){vec2 o=vec2(length(u.xz),-u.y);return length(o-v*max(dot(o,v),0.))*(o.x*v.y-o.y*v.x<0.?-1.:1.);}float d(vec3 u,float v,float o){vec2 f=vec2(length(u.xz)-2.*v+.05,abs(u.y)-o);return min(max(f.x,f.y),0.)+length(max(f,0.))-.05;}float opWi(vec3 v,vec3 f,float o,vec2 m){v=opTr(v,vec3(m.xy,0));v.xy=opRo(v.xy,o);v.yz=opRo(v.yz,PI*.5);v=u(v,f);float z=d(v,1.,.1);return d(z,f);}vec2 opBu(vec3 u,float o){u/=1.4;vec3 v=u;v.yz=opRo(v.yz,-PI*.5);vec2 f=vec2(10,.6);v.x=abs(v.x);v.xz=opRo(v.xz,PI*sin(sin(uTimelineTime*f.x+o)*cos(uTimelineTime*f.y+o))*.3);float m=opWi(v,vec3(.4,.3,.24)*.2,PI*-.3,vec2(.5,.4)*.2),z=opWi(v,vec3(.32,.3,.2)*.2,PI*.3,vec2(.4,-.4)*.2);return vec2(min(m,z),0);}vec2 opFl(vec3 v,float f){vec2 m=vec2(1e4,-1e4);v/=1.;v.y-=-.8;float r=.1;r=sin(uTimelineTime*1.4+.2+f)*.5;float z=-.1;z=cos(uTimelineTime*1.6+.1+f)*-.5;float l=v.y*sin(v.y*r),y=v.y*sin(v.y*z),s=sin(1.12*r)*.28,P=sin(1.12*z)*.28;mat2 n=o(-1.12*r),x=o(1.12*z);vec3 p=v;p=opTr(p,vec3(l,.28,y));float c=d(p,.015,.28);m=o(m,vec2(c,1));vec3 i=v;i=opTr(i,vec3(s,.56,P));i.yz=opRo(i.yz,PI*.5);i.xz*=n;i.yz*=x;i.xy=d(i.xy);i=opTr(i,vec3(0,.2,sin(i.y*5.)*.105));i.yz=opRo(i.yz,PI*.5);vec3 S=vec3(.08,.2,.2);i=u(i,S);float G=d(i,.4,.01);G=d(G,S);m=o(m,vec2(G,2));vec3 O=v;O=opTr(O,vec3(s,.59,P));float h=dfSp(O,.04);return o(m,vec2(h,3));}float opDb(float u,float v,float f,float o,float m,float z){return mix(mix(mix(v,f,smoothstep(0.,.25,u)),mix(f,o,smoothstep(.25,.5,u)),smoothstep(.25,.5,u)),mix(mix(o,m,smoothstep(.5,.75,u)),mix(m,z,smoothstep(.75,1.,u)),smoothstep(.5,.75,u)),smoothstep(.5,1.,u));}float opTb(float u,float v,float f,float o){return mix(mix(v,f,smoothstep(0.,.5,u)),mix(f,o,smoothstep(.5,1.,u)),smoothstep(.5,1.,u));}
#define BN 16
#define FS 1.4
#define CS.25
#define MS.35
uniform vec3 uCP,uBPs[BN],uGPs[4];uniform float uGS;uniform vec4 uGSs[4];uniform float uOMR;uniform vec3 uORo;uniform float uMR;float u(vec3 u){return sin(u.x*4.+uTimelineTime*3.4)*.025+.025+(cos(u.y*3.+uTimelineTime*3.2)*.025+.025)+(sin(u.z*3.5+uTimelineTime*3.)*.025+.025)+.01;}float dfMC(vec3 u){return dfSp(u,FS);}float diMAt(vec3 u){return 1.-smoothstep(1.,1.8,length(u-uCP));}float dfMB(vec3 v,float f){for(int o=0;o<BN;o++){vec3 m=opTr(v,uBPs[o].xyz);float z=dfSp(m,CS*uGS);f=opSm(f,z,MS);}f+=u(v)*diMAt(v)*uGS;return f;}float dfMBs(vec3 u){float v=dfSp(opTr(u,uCP),FS*uGS);return dfMB(u,v);}vec2 opMo(vec2 u,vec2 v,float f){return mix(u,v,f);}vec2 o(vec3 u,float v,float f){vec3 o=mod(u*f,2.)-1.;f*=3.;vec3 m=abs(1.-3.*abs(o));float z=(min(max(m.x,m.y),min(max(m.y,m.z),max(m.z,m.x)))-1.)/f;return vec2(max(v,z),f);}float dfMe(vec3 v,float u){v/=u;v/=.5;float f=dfBo(v,vec3(1));vec2 m=vec2(f,1);m=o(v,m.x,m.y);m=o(v,m.x,m.y);m=o(v,m.x,m.y);return m.x*u;}vec3 opPrf(vec3 v,float u,float f){v=abs(v)-1.18;v=abs(v)-1.2;v.xz*=o(u+.1+uTimelineTime*.8+f);v.xy*=o(u+.8+sin(uTimelineTime)*.4+f);return v;}float dfPr(vec3 v,float u,float f){v/=f;vec3 m=v;m.xy*=o(uTimelineTime*.8+u);float z=dfTo(m,vec2(.8,.05));vec3 i=v;i.yz*=o(uTimelineTime*1.2+u);float d=dfTo(i,vec2(.8,.05)),s=dfOc(v,.6),y=opSm(opSm(z,d,.5),s,.5);return y*f;}
#pragma RAYMARCH_SCENE
vec3 n(vec3 u){vec3 v=vec3(0);for(int f=0;f<4;f++){vec3 o=.5773*(2.*vec3(f+3>>1&1,f>>1&1,f&1)-1.);v+=o*dfScene(u+o*1e-4).x;}return normalize(v);}vec3 d(vec2 u,vec3 v,float o,float f){vec2 m=u*2.-1.;float z=tan(o*3.141592/180.*.5);vec3 s=v,i=normalize(cross(s,vec3(0,1,0)));return normalize(z*f*i*m.x+normalize(cross(i,s))*z*m.y+v);}float n(float v,float u,float o){return(v+u)/(u-o);}float u(float v,float u,float o){float f=u*v;return-f/(o*(v-1.)-f);}void n(float v,float u){if(v<u)discard;}uniform float uMetallic,uRoughness;uniform int uShadingModelId;uniform vec4 uEmissiveColor;
#pragma APPEND_UNIFORMS
uniform sampler2D uDepthTexture;uniform float uTargetWidth,uTargetHeight;
#ifdef USE_ALPHA_TEST
uniform float uAlphaTestThreshold;
#endif
in vec2 vUv;in vec3 vWorldPosition;
#define SHADING_MODEL_NUM 3.
struct GBufferA{vec3 baseColor;};struct GBufferB{vec3 normal;float shadingModelId;};struct GBufferC{float metallic;float roughness;};struct GBufferD{vec3 emissiveColor;};vec4 v(vec3 v,int u){float f=float(u)/SHADING_MODEL_NUM;return vec4(v*.5+.5,f);}layout(location=0) out vec4 outGBufferA;layout(location=1) out vec4 outGBufferB;layout(location=2) out vec4 outGBufferC;layout(location=3) out vec4 outGBufferD;void main(){vec4 m=vec4(0,0,0,1);vec3 o=vec3(0,0,1),f=uViewPosition,z=d(vUv,uViewDirection,uFov,uAspect);vec2 i=vec2(0);float r=uNearClip;vec3 s=f;float y=EPS;for(int l=0;l<SI;l++){s=f+z*r;i=dfScene(s);r+=i.x;if(r>uFarClip||i.x<=y)break;}if(i.x>y)discard;float p=texelFetch(uDepthTexture,ivec2(gl_FragCoord.xy),0).x,P=u(p,uNearClip,uFarClip),l=n((uViewMatrix*vec4(s,1)).z,uNearClip,uFarClip);if(l>=P)discard;vec4 O=uProjectionMatrix*uViewMatrix*vec4(s,1);gl_FragDepth=O.z/O.w*.5+.5;if(i.x>0.)o=n(s);
#ifdef USE_ALPHA_TEST
n(m.w,uAlphaTestThreshold);
#endif
m.xyz=pow(m.xyz,vec3(2.2));outGBufferA=vec4(m.xyz,1);outGBufferB=v(o,uShadingModelId);outGBufferC=vec4(uMetallic,uRoughness,0,1);outGBufferD=vec4(uEmissiveColor.xyz.xyz,1);}`;