import {
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_SUN_POSITION,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_SUN_INTENSITY,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_PLANET_RADIUS,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_ATMOSPHERE_RADIUS,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_RAYLEIGH_COEFFICIENT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_COEFFICIENT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_RAYLEIGH_SCALE_HEIGHT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_SCALE_HEIGHT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_SCATTERING_DIRECTION,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_CAMERA_ALTITUDE,
} from '../src/PaleGL/actors/meshes/proceduralAtmosphereSkyboxConstants';

// JSON最適化で丸めたくないプロパティ名のリスト
export const JSON_OPTIMIZER_EXCLUDE_KEYS = [
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_SUN_POSITION,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_SUN_INTENSITY,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_PLANET_RADIUS,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_ATMOSPHERE_RADIUS,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_RAYLEIGH_COEFFICIENT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_COEFFICIENT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_RAYLEIGH_SCALE_HEIGHT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_SCALE_HEIGHT,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_MIE_SCATTERING_DIRECTION,
    PROCEDURAL_ATMOSPHERE_SKYBOX_PROPERTY_NAME_CAMERA_ALTITUDE,
];

// JSON最適化のデフォルト設定
export const JSON_OPTIMIZER_DEFAULT_OPTIONS = {
    enableRound: false,
    decimalPlaces: 5,
    verbose: false,
    excludeKeys: JSON_OPTIMIZER_EXCLUDE_KEYS,
} as const;
