import {
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_BASE_COLOR_INDEX,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_BASE_COLOR_PROPERTY_NAME,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_EMISSIVE_COLOR_INDEX,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_EMISSIVE_COLOR_PROPERTY_NAME,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_METALLIC_INDEX,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_METALLIC_PROPERTY_NAME,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_ROUGHNESS_INDEX,
    MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_ROUGHNESS_PROPERTY_NAME,
} from '@/Marionetter/types';
import { createMaterialController, MaterialController } from '@/PaleGL/components/materialController.ts';
import {
    UNIFORM_NAME_BASE_COLOR,
    UNIFORM_NAME_EMISSIVE_COLOR,
    UNIFORM_NAME_METALLIC,
    UNIFORM_NAME_ROUGHNESS,
} from '@/PaleGL/constants';

const bindings = new Map([
    // prettier-ignore
    [
        MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_BASE_COLOR_PROPERTY_NAME,
        UNIFORM_NAME_BASE_COLOR
    ],
    [
        MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_METALLIC_PROPERTY_NAME,
        UNIFORM_NAME_METALLIC,
    ],
    [
        MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_ROUGHNESS_PROPERTY_NAME,
        UNIFORM_NAME_ROUGHNESS,
    ],
    [
        MARIONETTER_GBUFFER_MATERIAL_CONTROLLER_DATA_EMISSIVE_COLOR_PROPERTY_NAME,
        UNIFORM_NAME_EMISSIVE_COLOR,
    ],
]);

// timeline から操作される
export const createGBufferMaterialController = (): MaterialController => {
    return createMaterialController('GBufferMaterialController', bindings);
};
