import { Renderer } from '@/PaleGL/core/renderer.ts';
import { Color, copyColor, createColorFromHex } from '@/PaleGL/math/color.ts';
import { RawVector3, setV3, Vector3 } from '@/PaleGL/math/vector3.ts';
import {
    BLOOM_PASS_PARAMETERS_PROPERTY_ENABLED,
    BLOOM_PASS_PARAMETERS_PROPERTY_THRESHOLD,
    BLOOM_PASS_PARAMETERS_PROPERTY_TONE,
    BLOOM_PASS_PARAMETERS_PROPERTY_BLOOM_AMOUNT,
    BLOOM_PASS_PARAMETERS_KEY_ENABLED,
    BLOOM_PASS_PARAMETERS_KEY_THRESHOLD,
    BLOOM_PASS_PARAMETERS_KEY_TONE,
    BLOOM_PASS_PARAMETERS_KEY_BLOOM_AMOUNT,
} from '@/PaleGL/postprocess/bloomPass.ts';
import {
    CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_ENABLED,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_SCALE,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_POWER,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_ENABLED,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_SCALE,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_POWER,
    CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_BLEND_RATE,
} from '@/PaleGL/postprocess/chromaticAberrationPass.ts';
import {
    DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_ENABLED,
    DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_FOCUS_DISTANCE,
    DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_FOCUS_RANGE,
    DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_BOKEH_RADIUS,
    DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_ENABLED,
    DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_FOCUS_DISTANCE,
    DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_FOCUS_RANGE,
    DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_BOKEH_RADIUS,
} from '@/PaleGL/postprocess/depthOfFieldPass.ts';
import {
    FOG_PASS_PARAMETERS_PROPERTY_ENABLED,
    FOG_PASS_PARAMETERS_PROPERTY_FOG_COLOR,
    FOG_PASS_PARAMETERS_PROPERTY_FOG_STRENGTH,
    FOG_PASS_PARAMETERS_PROPERTY_FOG_DENSITY,
    FOG_PASS_PARAMETERS_PROPERTY_FOG_DENSITY_ATTENUATION,
    FOG_PASS_PARAMETERS_PROPERTY_FOG_END_HEIGHT,
    FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_START,
    FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_POWER,
    FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_END,
    FOG_PASS_PARAMETERS_PROPERTY_SSS_FOG_RATE,
    FOG_PASS_PARAMETERS_PROPERTY_SSS_FOG_COLOR,
    FOG_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    FOG_PASS_PARAMETERS_KEY_ENABLED,
    FOG_PASS_PARAMETERS_KEY_FOG_COLOR,
    FOG_PASS_PARAMETERS_KEY_FOG_STRENGTH,
    FOG_PASS_PARAMETERS_KEY_FOG_DENSITY,
    FOG_PASS_PARAMETERS_KEY_FOG_DENSITY_ATTENUATION,
    FOG_PASS_PARAMETERS_KEY_FOG_END_HEIGHT,
    FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_START,
    FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_POWER,
    FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_END,
    FOG_PASS_PARAMETERS_KEY_SSS_FOG_RATE,
    FOG_PASS_PARAMETERS_KEY_SSS_FOG_COLOR,
    FOG_PASS_PARAMETERS_KEY_BLEND_RATE,
} from '@/PaleGL/postprocess/fogPass.ts';
import {
    GLITCH_PASS_PARAMETERS_PROPERTY_ENABLED,
    GLITCH_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    GLITCH_PASS_PARAMETERS_KEY_ENABLED,
    GLITCH_PASS_PARAMETERS_KEY_BLEND_RATE,
} from '@/PaleGL/postprocess/glitchPass.ts';
import {
    LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_ENABLED,
    LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_RATIO,
    LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_PASS_SCALE_BASE,
    LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_RAY_STEP_STRENGTH,
    LIGHT_SHAFT_PASS_PARAMETERS_KEY_ENABLED,
    LIGHT_SHAFT_PASS_PARAMETERS_KEY_RATIO,
    LIGHT_SHAFT_PASS_PARAMETERS_KEY_BLEND_RATE,
    LIGHT_SHAFT_PASS_PARAMETERS_KEY_PASS_SCALE_BASE,
    LIGHT_SHAFT_PASS_PARAMETERS_KEY_RAY_STEP_STRENGTH,
} from '@/PaleGL/postprocess/lightShaftPass.ts';
import {
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_ENABLED,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_BIAS,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_JITTER_SIZE,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_SHARPNESS,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_STRENGTH,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_RATIO,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_RAY_STEP_MULTIPLIER,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_ENABLED,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_BIAS,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_JITTER_SIZE,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_SHARPNESS,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_STRENGTH,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_RATIO,
    SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_RAY_STEP_MULTIPLIER,
} from '@/PaleGL/postprocess/screenSpaceShadowPass.ts';
import {
    SSAO_PASS_PARAMETERS_PROPERTY_ENABLED,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_SAMPLE_LENGTH,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_BIAS,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_MIN_DISTANCE,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_MAX_DISTANCE,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_COLOR,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_POWER,
    SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_STRENGTH,
    SSAO_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    SSAO_PASS_PARAMETERS_PROPERTY_SAMPLING_TEXTURE,
    SSAO_PASS_PARAMETERS_KEY_ENABLED,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_SAMPLE_LENGTH,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_BIAS,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_MIN_DISTANCE,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_MAX_DISTANCE,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_COLOR,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_POWER,
    SSAO_PASS_PARAMETERS_KEY_OCCLUSION_STRENGTH,
    SSAO_PASS_PARAMETERS_KEY_BLEND_RATE,
    SSAO_PASS_PARAMETERS_KEY_SAMPLING_TEXTURE,
} from '@/PaleGL/postprocess/ssaoPass.ts';
import {
    SSR_PASS_PARAMETERS_PROPERTY_ENABLED,
    SSR_PASS_PARAMETERS_PROPERTY_RAY_DEPTH_BIAS,
    SSR_PASS_PARAMETERS_PROPERTY_RAY_NEAREST_DISTANCE,
    SSR_PASS_PARAMETERS_PROPERTY_RAY_MAX_DISTANCE,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_THICKNESS,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_JITTER_SIZE_X,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_JITTER_SIZE_Y,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_FADE_MIN_DISTANCE,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_FADE_MAX_DISTANCE,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_X,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_X,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_Y,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_Y,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_ROUGHNESS_POWER,
    SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_ADDITIONAL_RATE,
    SSR_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    SSR_PASS_PARAMETERS_KEY_ENABLED,
    SSR_PASS_PARAMETERS_KEY_RAY_DEPTH_BIAS,
    SSR_PASS_PARAMETERS_KEY_RAY_NEAREST_DISTANCE,
    SSR_PASS_PARAMETERS_KEY_RAY_MAX_DISTANCE,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_THICKNESS,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_JITTER_SIZE_X,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_JITTER_SIZE_Y,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_FADE_MIN_DISTANCE,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_FADE_MAX_DISTANCE,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_X,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_X,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_Y,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_Y,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_ROUGHNESS_POWER,
    SSR_PASS_PARAMETERS_KEY_REFLECTION_ADDITIONAL_RATE,
    SSR_PASS_PARAMETERS_KEY_BLEND_RATE,
} from '@/PaleGL/postprocess/ssrPass.ts';
import {
    STREAK_PASS_PARAMETERS_PROPERTY_ENABLED,
    STREAK_PASS_PARAMETERS_PROPERTY_THRESHOLD,
    STREAK_PASS_PARAMETERS_PROPERTY_STRETCH,
    STREAK_PASS_PARAMETERS_PROPERTY_COLOR,
    STREAK_PASS_PARAMETERS_PROPERTY_INTENSITY,
    STREAK_PASS_PARAMETERS_PROPERTY_VERTICAL_SCALE,
    STREAK_PASS_PARAMETERS_PROPERTY_HORIZONTAL_SCALE,
    STREAK_PASS_PARAMETERS_KEY_ENABLED,
    STREAK_PASS_PARAMETERS_KEY_THRESHOLD,
    STREAK_PASS_PARAMETERS_KEY_STRETCH,
    STREAK_PASS_PARAMETERS_KEY_COLOR,
    STREAK_PASS_PARAMETERS_KEY_INTENSITY,
    STREAK_PASS_PARAMETERS_KEY_VERTICAL_SCALE,
    STREAK_PASS_PARAMETERS_KEY_HORIZONTAL_SCALE,
} from '@/PaleGL/postprocess/streakPass.ts';
import {
    VIGNETTE_PASS_PARAMETERS_PROPERTY_ENABLED,
    VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_RADIUS_FROM,
    VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_RADIUS_TO,
    VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_POWER,
    VIGNETTE_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    VIGNETTE_PASS_PARAMETERS_KEY_ENABLED,
    VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_RADIUS_FROM,
    VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_RADIUS_TO,
    VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_POWER,
    VIGNETTE_PASS_PARAMETERS_KEY_BLEND_RATE,
} from '@/PaleGL/postprocess/vignettePass.ts';
import {
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_ENABLED,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RAY_STEP,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_DENSITY_MULTIPLIER,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RAY_JITTER_SIZE,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RATIO,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_ENABLED,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RAY_STEP,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_BLEND_RATE,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_DENSITY_MULTIPLIER,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RAY_JITTER_SIZE,
    VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RATIO,
} from '@/PaleGL/postprocess/volumetricLightPass.ts';

type NumToBoolConverter = (n: number, prop: unknown, key: string) => void;
const numToBoolConverter: NumToBoolConverter = (n: number, prop: unknown, key: string) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore-next-line
    (prop[key] as boolean) = n > 0.5;
};
type AssignVector3Converter = (v: RawVector3, prop: unknown, key: string) => void;
const assignVector3Converter: AssignVector3Converter = (v: RawVector3, prop: unknown, key: string) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore-next-line
    setV3(prop[key] as Vector3, v.x, v.y, v.z);
};
type AssignColorConverter = (c: string, prop: unknown, key: string) => void;
const assignColorConverter: AssignColorConverter = (hex: string, prop: unknown, key: string) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore-next-line
    copyColor(prop[key] as Color, createColorFromHex(hex));
};

export type PostProcessParametersConversionFunctions =
    | NumToBoolConverter
    | AssignVector3Converter
    | AssignColorConverter;

export type PostProcessParameterBindingValue =
    | [unknown, string]
    | [unknown, string, PostProcessParametersConversionFunctions];

export const buildPostProcessControllerEntries = (renderer: Renderer) => {
    const entries = [
        // screen space shadow ---
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_BIAS,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_BIAS],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_JITTER_SIZE,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_JITTER_SIZE, assignVector3Converter],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_SHARPNESS,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_SHARPNESS],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_STRENGTH,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_STRENGTH],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_RATIO,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_RATIO],
        ],
        [
            SCREEN_SPACE_SHADOW_PASS_PARAMETERS_PROPERTY_RAY_STEP_MULTIPLIER,
            [renderer.screenSpaceShadowPass, SCREEN_SPACE_SHADOW_PASS_PARAMETERS_KEY_RAY_STEP_MULTIPLIER],
        ],

        // ssao ---

        [
            SSAO_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_SAMPLE_LENGTH,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_SAMPLE_LENGTH],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_BIAS,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_BIAS],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_MIN_DISTANCE,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_MIN_DISTANCE],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_MAX_DISTANCE,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_MAX_DISTANCE],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_COLOR,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_COLOR, assignColorConverter],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_POWER,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_POWER],
        ],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_OCCLUSION_STRENGTH,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_OCCLUSION_STRENGTH],
        ],
        [SSAO_PASS_PARAMETERS_PROPERTY_BLEND_RATE, [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_BLEND_RATE]],
        [
            SSAO_PASS_PARAMETERS_PROPERTY_SAMPLING_TEXTURE,
            [renderer.ambientOcclusionPass, SSAO_PASS_PARAMETERS_KEY_SAMPLING_TEXTURE],
        ],

        // screen space reflection ---

        [SSR_PASS_PARAMETERS_PROPERTY_ENABLED, [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter]],
        [SSR_PASS_PARAMETERS_PROPERTY_RAY_DEPTH_BIAS, [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_RAY_DEPTH_BIAS]],
        [SSR_PASS_PARAMETERS_PROPERTY_RAY_NEAREST_DISTANCE, [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_RAY_NEAREST_DISTANCE]],
        [SSR_PASS_PARAMETERS_PROPERTY_RAY_MAX_DISTANCE, [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_RAY_MAX_DISTANCE]],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_THICKNESS,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_THICKNESS],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_JITTER_SIZE_X,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_JITTER_SIZE_X],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_RAY_JITTER_SIZE_Y,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_RAY_JITTER_SIZE_Y],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_FADE_MIN_DISTANCE,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_FADE_MIN_DISTANCE],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_FADE_MAX_DISTANCE,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_FADE_MAX_DISTANCE],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_X,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_X],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_X,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_X],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_Y,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MIN_Y],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_Y,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_SCREEN_EDGE_FADE_FACTOR_MAX_Y],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_ROUGHNESS_POWER,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_ROUGHNESS_POWER],
        ],
        [
            SSR_PASS_PARAMETERS_PROPERTY_REFLECTION_ADDITIONAL_RATE,
            [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_REFLECTION_ADDITIONAL_RATE],
        ],
        [SSR_PASS_PARAMETERS_PROPERTY_BLEND_RATE, [renderer.ssrPass, SSR_PASS_PARAMETERS_KEY_BLEND_RATE]],

        // light shaft ---

        [
            LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.lightShaftPass, LIGHT_SHAFT_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_RATIO, [renderer.lightShaftPass, LIGHT_SHAFT_PASS_PARAMETERS_KEY_RATIO]],
        [
            LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
            [renderer.lightShaftPass, LIGHT_SHAFT_PASS_PARAMETERS_KEY_BLEND_RATE],
        ],
        [
            LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_PASS_SCALE_BASE,
            [renderer.lightShaftPass, LIGHT_SHAFT_PASS_PARAMETERS_KEY_PASS_SCALE_BASE],
        ],
        [
            LIGHT_SHAFT_PASS_PARAMETERS_PROPERTY_RAY_STEP_STRENGTH,
            [renderer.lightShaftPass, LIGHT_SHAFT_PASS_PARAMETERS_KEY_RAY_STEP_STRENGTH],
        ],

        // volumetric light ---

        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RAY_STEP,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RAY_STEP],
        ],
        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_BLEND_RATE],
        ],
        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_DENSITY_MULTIPLIER,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_DENSITY_MULTIPLIER],
        ],
        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RAY_JITTER_SIZE,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RAY_JITTER_SIZE, assignVector3Converter],
        ],
        [
            VOLUMETRIC_LIGHT_PASS_PARAMETERS_PROPERTY_RATIO,
            [renderer.volumetricLightPass, VOLUMETRIC_LIGHT_PASS_PARAMETERS_KEY_RATIO],
        ],

        // fog ---

        [FOG_PASS_PARAMETERS_PROPERTY_ENABLED, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter]],
        [
            FOG_PASS_PARAMETERS_PROPERTY_FOG_COLOR,
            [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_FOG_COLOR, assignColorConverter],
        ],
        [FOG_PASS_PARAMETERS_PROPERTY_FOG_STRENGTH, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_FOG_STRENGTH]],
        [FOG_PASS_PARAMETERS_PROPERTY_FOG_DENSITY, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_FOG_DENSITY]],
        [
            FOG_PASS_PARAMETERS_PROPERTY_FOG_DENSITY_ATTENUATION,
            [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_FOG_DENSITY_ATTENUATION],
        ],
        [FOG_PASS_PARAMETERS_PROPERTY_FOG_END_HEIGHT, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_FOG_END_HEIGHT]],
        [FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_START, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_START]],
        [FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_POWER, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_POWER]],
        [FOG_PASS_PARAMETERS_PROPERTY_DISTANCE_FOG_END, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_DISTANCE_FOG_END]],
        [FOG_PASS_PARAMETERS_PROPERTY_SSS_FOG_RATE, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_SSS_FOG_RATE]],
        [
            FOG_PASS_PARAMETERS_PROPERTY_SSS_FOG_COLOR,
            [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_SSS_FOG_COLOR, assignColorConverter],
        ],
        [FOG_PASS_PARAMETERS_PROPERTY_BLEND_RATE, [renderer.fogPass, FOG_PASS_PARAMETERS_KEY_BLEND_RATE]],

        // dof ---

        [
            DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.depthOfFieldPass, DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_FOCUS_DISTANCE,
            [renderer.depthOfFieldPass, DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_FOCUS_DISTANCE],
        ],
        [
            DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_FOCUS_RANGE,
            [renderer.depthOfFieldPass, DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_FOCUS_RANGE],
        ],
        [
            DEPTH_OF_FIELD_PASS_PARAMETERS_PROPERTY_BOKEH_RADIUS,
            [renderer.depthOfFieldPass, DEPTH_OF_FIELD_PASS_PARAMETERS_KEY_BOKEH_RADIUS],
        ],

        // bloom ---

        [
            BLOOM_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.bloomPass, BLOOM_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [BLOOM_PASS_PARAMETERS_PROPERTY_THRESHOLD, [renderer.bloomPass, BLOOM_PASS_PARAMETERS_KEY_THRESHOLD]],
        [BLOOM_PASS_PARAMETERS_PROPERTY_TONE, [renderer.bloomPass, BLOOM_PASS_PARAMETERS_KEY_TONE]],
        [BLOOM_PASS_PARAMETERS_PROPERTY_BLOOM_AMOUNT, [renderer.bloomPass, BLOOM_PASS_PARAMETERS_KEY_BLOOM_AMOUNT]],

        // streak ---

        [
            STREAK_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [STREAK_PASS_PARAMETERS_PROPERTY_THRESHOLD, [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_THRESHOLD]],
        [STREAK_PASS_PARAMETERS_PROPERTY_STRETCH, [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_STRETCH]],
        [
            STREAK_PASS_PARAMETERS_PROPERTY_COLOR,
            [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_COLOR, assignColorConverter],
        ],
        [STREAK_PASS_PARAMETERS_PROPERTY_INTENSITY, [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_INTENSITY]],
        [STREAK_PASS_PARAMETERS_PROPERTY_VERTICAL_SCALE, [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_VERTICAL_SCALE]],
        [
            STREAK_PASS_PARAMETERS_PROPERTY_HORIZONTAL_SCALE,
            [renderer.streakPass, STREAK_PASS_PARAMETERS_KEY_HORIZONTAL_SCALE],
        ],

        // vignette ---

        [
            VIGNETTE_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.vignettePass, VIGNETTE_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_RADIUS_FROM,
            [renderer.vignettePass, VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_RADIUS_FROM],
        ],
        [
            VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_RADIUS_TO,
            [renderer.vignettePass, VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_RADIUS_TO],
        ],
        [
            VIGNETTE_PASS_PARAMETERS_PROPERTY_VIGNETTE_POWER,
            [renderer.vignettePass, VIGNETTE_PASS_PARAMETERS_KEY_VIGNETTE_POWER],
        ],
        [VIGNETTE_PASS_PARAMETERS_PROPERTY_BLEND_RATE, [renderer.vignettePass, VIGNETTE_PASS_PARAMETERS_KEY_BLEND_RATE]],

        // chromatic aberration ---

        [
            CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.chromaticAberrationPass, CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [
            CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_SCALE,
            [renderer.chromaticAberrationPass, CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_SCALE],
        ],
        [
            CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_POWER,
            [renderer.chromaticAberrationPass, CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_POWER],
        ],
        [
            CHROMATIC_ABERRATION_PASS_PARAMETERS_PROPERTY_BLEND_RATE,
            [renderer.chromaticAberrationPass, CHROMATIC_ABERRATION_PASS_PARAMETERS_KEY_BLEND_RATE],
        ],

        // glitch ---

        [
            GLITCH_PASS_PARAMETERS_PROPERTY_ENABLED,
            [renderer.glitchPass, GLITCH_PASS_PARAMETERS_KEY_ENABLED, numToBoolConverter],
        ],
        [GLITCH_PASS_PARAMETERS_PROPERTY_BLEND_RATE, [renderer.glitchPass, GLITCH_PASS_PARAMETERS_KEY_BLEND_RATE]],
    ] satisfies ReadonlyArray<readonly [string, PostProcessParameterBindingValue]>;

    return new Map<string, PostProcessParameterBindingValue>(entries);
};
