import {Actor} from "./Actor.js";
import {ActorTypes, UniformTypes} from "./../constants.js";
import {Material} from "../materials/Material.js";
import {generateDepthFragmentShader} from "../shaders/generateFragmentShader.js";

export class Mesh extends Actor {
    geometry;
    material;
    depthMaterial;
    castShadow;
    autoGenerateDepthMaterial;
    
    constructor({
        geometry,
        material,
        depthMaterial = null,
        actorType = ActorTypes.Mesh,
        castShadow = false,
        autoGenerateDepthMaterial = true
    }) {
        super(actorType);
        this.geometry = geometry;
        this.material = material;
        this.depthMaterial = depthMaterial;
        this.castShadow = !!castShadow;
        this.autoGenerateDepthMaterial = autoGenerateDepthMaterial;
    }
 
    start(options) {
        super.start(options);
        
        const { gpu } = options;

        if(
            !this.depthMaterial &&
            this.autoGenerateDepthMaterial
        ) {
            this.depthMaterial = new Material({
                gpu,
                vertexShader: this.material.vertexShader,
                fragmentShader: this.material.fragmentShader,
                uniforms: this.material.depthUniforms,
                faceSide: this.material.faceSide
            });
        }
    }
}